/* -*- Mode:C++; c-file-style:"gnu"; indent-tabs-mode:nil; -*- */
/*
 * Copyright (c) 2024 optimal_medium_v2 - ML Mobility NS3 Project
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation;
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

#ifndef NETMOB25_MOBILITY_MODEL_H
#define NETMOB25_MOBILITY_MODEL_H

#include "ns3/mobility-model.h"
#include "ns3/event-id.h"
#include "ns3/nstime.h"
#include "ns3/vector.h"
#include "ns3/geographic-positions.h"
#include <vector>
#include <cmath>
#include <memory>

namespace ns3 {

/**
 * \ingroup mobility
 * \brief Netmob25 mobility model using ML-generated trajectories
 *
 * This mobility model implements realistic mobility patterns generated by
 * machine learning models trained on NetMob25 dataset. The model can use
 * either pre-generated trajectories or real-time ML inference.
 * 
 * Generated for experiment: optimal_medium_v2
 */
class Netmob25MobilityModel : public MobilityModel
{
public:
  static TypeId GetTypeId (void);

  Netmob25MobilityModel ();
  virtual ~Netmob25MobilityModel ();

  /**
   * \brief Set the trajectory data for this node
   * \param trajectory Vector of positions (x, y) over time
   */
  void SetTrajectory (const std::vector<Vector>& trajectory);

  /**
   * \brief Set the model file path for ML generation
   * \param modelPath path to the model.p file
   */
  void SetModelPath (const std::string& modelPath);

  /**
   * \brief Set simulation parameters
   * \param startTime start time for mobility
   * \param updateInterval time between position updates
   * \param scaleX scaling factor for X coordinates (meters)
   * \param scaleY scaling factor for Y coordinates (meters)
   */
  void SetSimulationParams (Time startTime, Time updateInterval, double scaleX = 1000.0, double scaleY = 1000.0);

private:
  virtual Vector DoGetPosition (void) const;
  virtual void DoSetPosition (const Vector& position);
  virtual Vector DoGetVelocity (void) const;

  /**
   * \brief Initialize the mobility model
   */
  void Initialize (void);

  /**
   * \brief Update position based on current step
   */
  void UpdatePosition (void);

  /**
   * \brief Generate trajectory using ML model
   */
  void GenerateMLTrajectory (void);

#ifdef HAVE_LIBTORCH
  /**
   * \brief Load the ML model
   */
  void LoadModel (void);
  
  /**
   * \brief Generate trajectory from the ML model
   */
  std::vector<std::vector<double>> GenerateFromModel (int trip_length);
#endif

  // Trajectory data
  std::vector<Vector> m_trajectory;
  uint32_t m_currentStep;
  uint32_t m_totalSteps;
  
  // Timing parameters
  Time m_startTime;
  Time m_updateInterval;
  EventId m_updateEvent;
  
  // Scaling parameters
  double m_scaleX;
  double m_scaleY;
  
  // ML generation parameters
  std::string m_modelPath;
  std::string m_transportMode;
  int m_tripLength;
  
  // Current state
  Vector m_currentPosition;
  Vector m_currentVelocity;
  mutable Time m_lastUpdate;
  bool m_initialized;

#ifdef HAVE_LIBTORCH
  // Private implementation to hide LibTorch dependencies
  class Impl;
  std::unique_ptr<Impl> m_pImpl;
#endif
};

} // namespace ns3

#endif /* NETMOB25_MOBILITY_MODEL_H */