_target_: ml_mobility_ns3.models.vae_hierarchical.HierarchicalTrajectoryVAE
name: vae_hierarchical

# Architecture parameters
input_dim: 3
hidden_dim: 256
segment_latent_dim: 32
global_latent_dim: 64
condition_dim: 32
segment_length: 100
num_layers: 2
dropout: 0.1

# Conditioning
num_transport_modes: 5
sequence_length: 2000