batch_size: 32
epochs: 500
learning_rate: 0.001
val_split: 0.1
gradient_clip: 1.0
early_stopping_patience: 30
lr_scheduler_patience: 15
lr_scheduler_factor: 0.5

# Loss configuration
loss:
  type: simple_vae
  params:
    beta:
      type: linear_annealing
      params:
        start: 0.0
        end: 1.0
        anneal_epochs: 100
    free_bits:
      enabled: true
      lambda_free_bits: 2.0