batch_size: 32
epochs: 100
learning_rate: 0.001
val_split: 0.2
gradient_clip: 1.0

loss:
  type: simple_vae 
  params:
    beta: 1.0

lr_scheduler_patience: 5
lr_scheduler_factor: 0.5
early_stopping_patience: 10