batch_size: 64
epochs: 100
learning_rate: 1e-4
beta: 0.001
gradient_clip: 1.0
val_split: 0.15
early_stopping_patience: 20
lr_scheduler_patience: 10
lr_scheduler_factor: 0.5
checkpoint_dir: checkpoints
