# @package _global_
defaults:
  - override /hydra/sweeper: basic

accelerator: gpu
devices: [4]

hydra:
  sweeper:
    params:
      model.hidden_dim: 128,256,512
      model.latent_dim: 16,32,64
      training.batch_size: 16,32,64
      loss.params.beta: 0.5,1.0,2.0