# @package _global_
defaults:
  - override /hydra/sweeper: optuna
  - override /hydra/launcher: joblib

hydra:
  sweeper:
    sampler:
      _target_: optuna.samplers.TPESampler
      seed: 42
    direction: minimize
    n_trials: 50
    params:
      model.hidden_dim: choice(64, 128, 256, 512)
      model.latent_dim: choice(16, 32, 64)
      training.batch_size: choice(16, 32, 64, 128)
      loss.params.beta: interval(0.1, 5.0)